#!/bin/bash
# ============================================================
# REZ Ecosystem — Create .gitignore entries for each service
# ============================================================
# Usage:
#   ./scripts/create-gitignore.sh
# ============================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }

# Project root directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

# Docker deployment entries
DOCKER_ENTRIES="
# ============================================================
# Docker & Deployment
# ============================================================
.dockerignore
docker-compose.override.yml
.docker
Dockerfile.prod
.dockerignore
"

# Environment entries
ENV_ENTRIES="
# ============================================================
# Environment & Secrets
# ============================================================
.env
.env.local
.env.development
.env.production
.env.staging
.env.test
.env.*.local
*.env
secrets.json
credentials.json
service-account.json
"

# Build artifacts entries
BUILD_ENTRIES="
# ============================================================
# Build Artifacts
# ============================================================
dist
build
.next
out
.turbo
coverage
.nyc_output
*.tsbuildinfo
"

# Node modules entries
NODE_ENTRIES="
# ============================================================
# Dependencies
# ============================================================
node_modules
.npm
.yarn
pnpm-store
.pnpm-store
"

# IDE entries
IDE_ENTRIES="
# ============================================================
# IDE & Editor
# ============================================================
.vscode
.idea
*.swp
*.swo
*~
.DS_Store
Thumbs.db
"

# Log files
LOG_ENTRIES="
# ============================================================
# Logs
# ============================================================
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*
"

# Cache entries
CACHE_ENTRIES="
# ============================================================
# Cache
# ============================================================
.cache
.parcel-cache
__pycache__
*.pyc
.rubocop-cache
.eslintcache
.stylelintcache
"

# Function to append entries to .gitignore
add_to_gitignore() {
    local dir="$1"
    local gitignore="$dir/.gitignore"

    if [ ! -d "$dir" ]; then
        return
    fi

    log_info "Processing $dir..."

    # Create .gitignore if it doesn't exist
    if [ ! -f "$gitignore" ]; then
        touch "$gitignore"
        echo "# Generated by scripts/create-gitignore.sh" > "$gitignore"
        echo "" >> "$gitignore"
    fi

    # Check if entries already exist
    if grep -q "Docker & Deployment" "$gitignore" 2>/dev/null; then
        echo "  Skipping $dir - already has deployment entries"
        return
    fi

    # Append entries
    {
        echo ""
        echo "$DOCKER_ENTRIES"
        echo "$ENV_ENTRIES"
        echo "$BUILD_ENTRIES"
        echo "$NODE_ENTRIES"
        echo "$IDE_ENTRIES"
        echo "$LOG_ENTRIES"
        echo "$CACHE_ENTRIES"
    } >> "$gitignore"

    log_success "Updated $gitignore"
}

# Main services to process
SERVICES=(
    "rez-now"
    "verify-service"
    "rez-try"
    "rez-auth-service"
    "rez-merchant-service"
    "Rendez/rendez-backend"
    "Hotel OTA"
    "nextabizz/apps/web"
)

log_info "Creating .gitignore entries for services..."
echo ""

for service in "${SERVICES[@]}"; do
    # Handle paths with spaces
    if [ -d "$service" ]; then
        add_to_gitignore "$service"
    fi
done

echo ""
log_success "Gitignore entries created!"
echo ""
echo "Note: Review each .gitignore file to ensure no legitimate files are excluded."
