import { TrialCard, HistoryItem, CoinsData, ScoreData, Mission, BadgesData, LeaderboardData, SurpriseData, Bundle, ActiveBundle, Campaign } from './types';

export const MOCK_DATA = {
  trials: [
    {
      id: '1',
      title: 'Full Spa Massage Experience',
      category: 'Wellness',
      categoryEmoji: '💆',
      merchant: { id: 'm1', name: 'Serenity Spa', image: '' },
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
      description: 'Relax with a full body massage and aromatherapy session',
      coinPrice: 80,
      commitmentFee: 49,
      originalPrice: 599,
      distance: 1.2,
      distanceUnit: 'km',
      slotsRemaining: 5,
      slotsTotal: 20,
      rating: 4.8,
      ratingCount: 124,
      rewards: { coinsEarned: 50, brandedCoinsEarned: 20 },
    },
    {
      id: '2',
      title: 'Café Breakfast Combo',
      category: 'Food',
      categoryEmoji: '☕',
      merchant: { id: 'm2', name: 'Morning Brew Café', image: '' },
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800',
      description: 'Enjoy our signature breakfast with unlimited coffee',
      coinPrice: 40,
      commitmentFee: 29,
      originalPrice: 299,
      distance: 0.8,
      distanceUnit: 'km',
      slotsRemaining: 12,
      slotsTotal: 30,
      rating: 4.5,
      ratingCount: 89,
      rewards: { coinsEarned: 25, brandedCoinsEarned: 10 },
    },
    {
      id: '3',
      title: 'Gym Day Pass',
      category: 'Fitness',
      categoryEmoji: '💪',
      merchant: { id: 'm3', name: 'FitZone Gym', image: '' },
      image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800',
      description: 'Full day access to all gym facilities and classes',
      coinPrice: 60,
      commitmentFee: 39,
      originalPrice: 499,
      distance: 2.1,
      distanceUnit: 'km',
      slotsRemaining: 8,
      slotsTotal: 25,
      rating: 4.6,
      ratingCount: 67,
      rewards: { coinsEarned: 40, brandedCoinsEarned: 15 },
    },
    {
      id: '4',
      title: 'Salon Hair Treatment',
      category: 'Beauty',
      categoryEmoji: '💅',
      merchant: { id: 'm4', name: 'Glow Studio', image: '' },
      image: 'https://images.unsplash.com/photo-1560066984-138daaa9325d?w=800',
      description: 'Keratin treatment with hair wash and styling',
      coinPrice: 100,
      commitmentFee: 59,
      originalPrice: 799,
      distance: 1.5,
      distanceUnit: 'km',
      slotsRemaining: 3,
      slotsTotal: 15,
      rating: 4.9,
      ratingCount: 201,
      rewards: { coinsEarned: 60, brandedCoinsEarned: 25 },
    },
    {
      id: '5',
      title: 'Yoga Session',
      category: 'Wellness',
      categoryEmoji: '🧘',
      merchant: { id: 'm5', name: 'Zen Yoga Studio', image: '' },
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
      description: '60-minute guided yoga session for all levels',
      coinPrice: 50,
      commitmentFee: 29,
      originalPrice: 399,
      distance: 0.5,
      distanceUnit: 'km',
      slotsRemaining: 10,
      slotsTotal: 20,
      rating: 4.7,
      ratingCount: 156,
      rewards: { coinsEarned: 35, brandedCoinsEarned: 12 },
    },
    {
      id: '6',
      title: 'Artisan Coffee Tasting',
      category: 'Food',
      categoryEmoji: '☕',
      merchant: { id: 'm6', name: 'Bean & Brew', image: '' },
      image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
      description: 'Premium coffee tasting experience with 5 varieties',
      coinPrice: 30,
      commitmentFee: 19,
      originalPrice: 199,
      distance: 1.8,
      distanceUnit: 'km',
      slotsRemaining: 15,
      slotsTotal: 25,
      rating: 4.4,
      ratingCount: 78,
      rewards: { coinsEarned: 20, brandedCoinsEarned: 8 },
    },
  ] as TrialCard[],

  history: [
    {
      bookingId: 'b1',
      trialId: '1',
      title: 'Full Spa Massage Experience',
      merchant: 'Serenity Spa',
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
      coinsPaid: 80,
      commitmentFeePaid: 49,
      bookingDate: '2024-01-15T10:00:00Z',
      status: 'active' as const,
      qrToken: 'mock-qr-active',
      qrExpiresAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
      validUntil: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      bookingId: 'b2',
      trialId: '2',
      title: 'Café Breakfast Combo',
      merchant: 'Morning Brew Café',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800',
      coinsPaid: 40,
      commitmentFeePaid: 29,
      bookingDate: '2024-01-10T09:00:00Z',
      status: 'completed' as const,
      rating: 5,
      reviewText: 'Amazing breakfast and great service!',
      completedDate: '2024-01-10T10:30:00Z',
    },
  ] as HistoryItem[],

  coins: {
    totalBalance: 340,
    buckets: [
      { amount: 200, expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(), source: 'pack' as const },
      { amount: 140, expiresAt: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(), source: 'earned' as const },
    ],
    recentTransactions: [
      { id: 't1', type: 'earn' as const, amount: 50, description: 'Completed: Full Spa Massage', date: '2024-01-15' },
      { id: 't2', type: 'spend' as const, amount: -80, description: 'Booked: Full Spa Massage', date: '2024-01-15' },
      { id: 't3', type: 'earn' as const, amount: 25, description: 'Completed: Café Breakfast', date: '2024-01-10' },
    ],
  } as CoinsData,

  score: {
    score: 2340,
    tier: 'adventurer' as const,
    nextTierPoints: 3500,
    nextTierName: 'Pioneer',
    stats: {
      categoriesTried: 8,
      merchantsDiscovered: 15,
      currentStreak: 5,
      reviewsGiven: 12,
    },
    recentEvents: [
      { id: 'e1', description: 'First beauty trial', points: 50, date: '2024-01-14', emoji: '💅' },
      { id: 'e2', description: 'Completed 5 trials', points: 100, date: '2024-01-12', emoji: '🎯' },
      { id: 'e3', description: 'Left a review', points: 25, date: '2024-01-10', emoji: '⭐' },
    ],
    leaderboardPercentile: 15,
    leaderboardCity: 'Mumbai',
  } as ScoreData,

  missions: [
    {
      id: 'ms1',
      title: 'Try 3 cafes this weekend',
      description: 'Visit 3 different café trials and earn bonus coins',
      category: 'Food',
      categoryEmoji: '☕',
      target: 3,
      completed: 1,
      reward: { rezCoins: 200, trialCoins: 50 },
      endsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      isCompleted: false,
      isExpired: false,
    },
  ] as Mission[],

  badges: {
    earned: [
      { category: 'food', categoryEmoji: '☕', level: 'Expert' as const, trialCount: 12, nextLevelThreshold: 15 },
      { category: 'beauty', categoryEmoji: '💅', level: 'Regular' as const, trialCount: 5, nextLevelThreshold: 10 },
      { category: 'fitness', categoryEmoji: '💪', level: 'Newcomer' as const, trialCount: 2, nextLevelThreshold: 5 },
    ],
    undiscovered: [
      { category: 'wellness', categoryEmoji: '🧘' },
      { category: 'home', categoryEmoji: '🏠' },
    ],
  } as BadgesData,

  leaderboard: {
    entries: [
      { rank: 1, name: 'Priya S.', score: 4520, trialCount: 28 },
      { rank: 2, name: 'Rahul M.', score: 3980, trialCount: 24 },
      { rank: 3, name: 'Aisha K.', score: 3450, trialCount: 21 },
      { rank: 4, name: 'Vikram J.', score: 2890, trialCount: 18 },
      { rank: 5, name: 'You', score: 2340, trialCount: 15, isCurrentUser: true },
    ],
    userRank: 5,
    userScore: 2340,
  } as LeaderboardData,

  surprise: {
    category: 'Spa',
    categoryEmoji: '💆',
    distance: '1.5 km',
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
  } as SurpriseData,

  bundles: [
    {
      id: 'bundle1',
      name: 'Wellness Starter',
      description: '3 spa & wellness trials',
      price: 249,
      originalPrice: 399,
      trialCount: 3,
      trialCoinsIncluded: 100,
      rezCoinsBonus: 50,
      validDays: 30,
      isFeatured: true,
    },
    {
      id: 'bundle2',
      name: 'Food Explorer',
      description: '5 café & restaurant trials',
      price: 399,
      originalPrice: 599,
      trialCount: 5,
      trialCoinsIncluded: 200,
      rezCoinsBonus: 100,
      validDays: 45,
    },
  ] as Bundle[],

  myBundles: [] as ActiveBundle[],

  campaigns: [
    {
      id: 'camp1',
      title: 'Festival Frenzy',
      description: 'Complete trials during the festival week',
      type: 'FESTIVAL' as const,
      goal: 'Complete 5 trials',
      reward: 'Double coins on all completions',
      endsAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      isJoined: true,
      isCompleted: false,
      progress: { completed: 2, target: 5 },
    },
  ] as Campaign[],
};
