import mongoose, { Document, Schema } from 'mongoose';

export interface ICreditProfile extends Document {
  userId: string;

  // External bureau score (Experian / CRIF)
  bureauScore?: number;
  bureauProvider?: string;        // 'experian' | 'crif'
  bureauFetchedAt?: Date;

  // REZ proprietary score (0–850)
  rezScore: number;
  rezScoreUpdatedAt: Date;

  // Scoring factors
  factors: {
    totalSpend30d: number;
    orderCount30d: number;
    avgOrderValue: number;
    visitFrequency: number;       // visits/week
    paymentHistory: number;       // 0–1 (fraction on-time)
    walletBalance: number;
    coinsBalance: number;
  };

  // Eligibility bands derived from rezScore
  eligibility: {
    maxLoanAmount: number;        // ₹
    maxCreditCardLimit: number;   // ₹
    bnplEnabled: boolean;
    bnplLimit: number;
  };

  // BE-FIN-018: Track frozen/inactive status for compliance
  isActive: boolean;
  isFrozen: boolean;
  frozenReason?: string;

  // Credit improvement tips (generated by intelligence engine)
  tips: string[];

  createdAt: Date;
  updatedAt: Date;
}

const CreditProfileSchema = new Schema<ICreditProfile>(
  {
    userId: { type: String, required: true, unique: true, index: true },
    bureauScore: { type: Number },
    bureauProvider: { type: String },
    bureauFetchedAt: { type: Date },
    rezScore: { type: Number, default: 0 },
    rezScoreUpdatedAt: { type: Date, default: Date.now },
    factors: {
      totalSpend30d: { type: Number, default: 0 },
      orderCount30d: { type: Number, default: 0 },
      avgOrderValue: { type: Number, default: 0 },
      visitFrequency: { type: Number, default: 0 },
      paymentHistory: { type: Number, default: 1 },
      walletBalance: { type: Number, default: 0 },
      coinsBalance: { type: Number, default: 0 },
    },
    eligibility: {
      maxLoanAmount: { type: Number, default: 0 },
      maxCreditCardLimit: { type: Number, default: 0 },
      bnplEnabled: { type: Boolean, default: false },
      bnplLimit: { type: Number, default: 0 },
    },
    // BE-FIN-018: Track frozen/inactive status
    isActive: { type: Boolean, default: true, index: true },
    isFrozen: { type: Boolean, default: false, index: true },
    frozenReason: { type: String },
    tips: [{ type: String }],
  },
  { timestamps: true },
);

// Add compound indexes for common query patterns
CreditProfileSchema.index({ isActive: 1, isFrozen: 1 });
CreditProfileSchema.index({ isActive: 1, createdAt: -1 });

export const CreditProfile = mongoose.model<ICreditProfile>('CreditProfile', CreditProfileSchema);
